feat: add lib entrypoint exemple
G-Epitech/MAYBDF-ArcadeShared pull request #11
Opened 2024-03-19 17:48 UTC by AxelF44

I added the examples of entry points that will have to be implemented for each library. It will therefore be necessary in the code first called the entrypoint which will allow to get the type of the libraries in order to know which entrypoint called.

2024-03-19 18:07 UTC, flavien-chenu requested changes

2024-03-19 18:07 UTC, flavien-chenu commented on types/LibraryType.hpp
> +    Renderer
```suggestion
    GAME,
    RENDERER
```

2024-03-19 18:07 UTC, flavien-chenu commented on exportRenderer.exemple
> +}
```suggestion
extern "C" shared::types::LibraryType arcadeLibGetType()
{
    return shared::types::LibraryType.RENDERER;
}
```

2024-03-19 18:07 UTC, flavien-chenu commented on exportGame.exemple
> +}
```suggestion
```suggestion
extern "C" shared::types::LibraryType arcadeLibGetType(void)
{
    return shared::types::LibraryType.GAME;
}
```
```

2024-03-19 18:07 UTC, flavien-chenu commented on exportGame.exemple
> +}
```suggestion
extern "C" std::unique_ptr<shared::games::IGame> arcadeLibGetGame(void)
{
    return std::make_unique<GameClass>(...);
}
```
ℹ️ **Here `GameClass` will be replaced by target game class**

2024-03-19 18:07 UTC, flavien-chenu commented on exportRenderer.exemple
> +}
```suggestion
extern "C" std::unique_ptr<shared::graphic::IRenderer> arcadeLibGetRenderer(void)
{
    return std::make_unique<RendererClass>(...);
}
```
ℹ️ **Here `RendererClas` will be replaced by target renderer class**

2024-03-19 18:07 UTC, flavien-chenu commented on exportGame.exemple
Put your file in `games/export.cpp.example` **not at root with name `exportGame.exemple`**

2024-03-19 18:07 UTC, flavien-chenu commented on exportRenderer.exemple
Put your file in `graphic/export.cpp.example` **not at root with name `exportRenderer.exemple`**

2024-03-21 11:57 UTC, Yann-Masson submitted a review, later dismissed

2024-03-21 17:39 UTC, Yann-Masson approved these changes, later dismissed

2024-03-21 17:41 UTC, BxptisteM approved these changes, later dismissed

2024-03-21 20:36 UTC, TekMath requested changes
If you add shareptr for Game and Display, please update UniqueGame type to SharedGame type

2024-03-21 21:43 UTC, sdragos1 submitted a review, later dismissed

2024-03-21 22:29 UTC, Yann-Masson submitted a review, later dismissed

2024-03-22 08:28 UTC, flavien-chenu approved these changes, later dismissed

2024-03-22 08:57 UTC, Yann-Masson approved these changes, later dismissed

2024-03-22 09:13 UTC, Yann-Masson approved these changes

2024-03-22 09:45 UTC, TekMath approved these changes
Let's make it!

2024-03-22 09:54 UTC, flavien-chenu approved these changes

2024-03-22 09:56 UTC, merged