Change texture positions to floats
G-Epitech/MAYBDF-ArcadeShared pull request #45
Opened 2024-04-04 21:03 UTC by sdragos1

## Changes made

Change positions to float to have more fluid games

Also added getScore() to IGame

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: because no
- [ ] I need help with writing tests

2024-04-04 21:05 UTC, flavien-chenu requested changes
Don't forget to change events positions in `grpahics` and `games`.

2024-04-04 21:05 UTC, AxelF44 submitted a review, later dismissed

2024-04-04 22:00 UTC, flavien-chenu approved these changes

2024-04-04 22:54 UTC, Yann-Masson approved these changes

2024-04-05 00:22 UTC, AxelF44 approved these changes

2024-04-05 07:29 UTC, TekMath approved these changes

2024-04-05 08:36 UTC, merged