Create games interfaces
G-Epitech/MAYBDF-ArcadeShared pull request #6
Opened 2024-03-16 19:46 UTC by TekMath

## Changes made

- Added Entity interface
- Added DisplayableEntity interface
- Added SoundProps type
- Added TextureProps type
- Added KeyData type
- Added GameManifest type
- Added Game interface
- Added Vector, UUid types

✨ Make unique_ptr nice to use

2024-03-16 20:09 UTC, BxptisteM submitted a review, later dismissed

2024-03-16 22:56 UTC, Yann-Masson requested changes
I have notice that some files use 2 spaces and some others 4 spaces as tabulation. Please update those files and make a choice : 2 spaces or 4 spaces.
Otherwise, it's a really great job! I'm proud to work with you!

2024-03-16 22:56 UTC, Yann-Masson commented on games/entity/IDisplayableEntity.hpp
> +** IEntity
This file doesn't name `IEntity` but `IDisplayableEntity`
```suggestion
** IDisplayableEntity
```

2024-03-16 22:56 UTC, Yann-Masson commented on games/types/GameManifest.hpp
> +#include <string>
Add a space between `#pragma once` and the `include `
```suggestion
#pragma once

#include <string>
```

2024-03-16 22:56 UTC, Yann-Masson commented on games/game/IGame.hpp
> +#include "../types/GameManifest.hpp"
```suggestion
#include <memory>
#include "../types/GameManifest.hpp"
```

2024-03-16 22:56 UTC, Yann-Masson commented on games/types/SoundProps.hpp
> +#include <memory>
```suggestion
#include <map>
#include <string>
#include <memory>
```

2024-03-16 22:56 UTC, Yann-Masson commented on games/types/TextureProps.hpp
> +#include "../../types/types.hpp"
```suggestion
#include <string>
#include "../../types/types.hpp"
```

2024-03-16 22:56 UTC, Yann-Masson commented on types/types.hpp
If you want

2024-03-17 10:47 UTC, sdragos1 approved these changes, later dismissed

2024-03-17 11:04 UTC, AxelF44 approved these changes, later dismissed

2024-03-18 09:15 UTC, Yann-Masson approved these changes
Dear Flavien and Mathéo,

I wanted to take a moment to extend my heartfelt congratulations and sincere appreciation for the outstanding contributions both of you have made to our project, especially in the recent pull request.

Flavien, your dedication to detail and your ability to tackle complex challenges head-on have been truly impressive. Your expertise and insights have consistently elevated the quality of our project, and your recent contributions in the pull request have once again highlighted your commitment to excellence.

Mathéo, your innovative thinking and proactive approach to problem-solving have been invaluable to our team. Your willingness to explore new ideas and your exceptional coding skills have greatly enhanced our project's capabilities. Your recent work in the pull request has been nothing short of exceptional, and it's clear that your passion for our project shines through in everything you do.

Together, your collaborative efforts have fostered a dynamic and supportive team environment. Your willingness to share knowledge, provide feedback, and support each other has been instrumental to our success. It's inspiring to see how your teamwork has propelled us forward, and I have no doubt that our project is stronger because of your combined efforts.

On behalf of the entire team, I want to express my deepest gratitude for your hard work, dedication, and unwavering commitment. Your contributions have not only helped us achieve our goals but have also set a high standard for excellence within our team.

Congratulations, Flavien and Mathéo, on a job well done! I look forward to continuing our journey together and achieving even greater milestones in the future.

Warm regards ✈,

2024-03-18 09:17 UTC, AxelF44 approved these changes

2024-03-18 10:41 UTC, sdragos1 approved these changes

2024-03-18 10:44 UTC, merged